[package]
name = "Proofly"
version = "1.0.0"
authors = []
license = "MIT"

[addresses]
proofly = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "aptos-cli-v9.5.0" }

[dev-addresses]

[dev-dependencies]
